# Generated by Django 5.2.6 on 2025-11-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.CharField(max_length=255)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('kit', models.CharField(blank=True, max_length=255, null=True)),
                ('service_repeat', models.IntegerField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
    ]
