# notifier/utils.py

from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from datetime import date, timedelta

APPLIANCE_NAME = "Bradford HydroMax Series Water Heater"
MODEL_NUMBER = "HX-75B-UL"
SERIAL_NUMBER = "SN-2847-9931-A"
REPLACEMENT_PART_SKU = "WHR-75B-KIT-2025"
LOCATION = "Mechanical Room 2B"
DAYS_REMAINING = 2


def _build_plaintext_body(replacement_date):
    return f"""
Maintenance Alert – Replacement Threshold Approaching

Appliance: {APPLIANCE_NAME}
Model: {MODEL_NUMBER}
Serial: {SERIAL_NUMBER}
Location: {LOCATION}

Status:
The appliance is approaching its end-of-service interval.
Days remaining: {DAYS_REMAINING}

Recommended Action:
Replacement Kit SKU: {REPLACEMENT_PART_SKU}

Projected Replacement Date: {replacement_date}

(This is a demonstration message.)
""".strip()


def _build_html_body(replacement_date):
    return f"""
<html>
<body style="font-family: Arial, sans-serif; color: #333; background-color: #f8f9fb; padding: 20px;">
  <div style="max-width: 600px; margin: auto; background: white; border-radius: 8px; 
              padding: 20px; box-shadow: 0 2px 6px rgba(0,0,0,0.15);">

    <h2 style="color: #0057b8; margin-top: 0;">
      Maintenance Alert: Replacement Threshold Approaching
    </h2>

    <p>The system has detected an appliance nearing its recommended replacement date.</p>

    <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
      <tr><td style="padding: 6px 0;"><strong>Appliance:</strong></td><td>{APPLIANCE_NAME}</td></tr>
      <tr><td style="padding: 6px 0;"><strong>Model:</strong></td><td>{MODEL_NUMBER}</td></tr>
      <tr><td style="padding: 6px 0;"><strong>Serial:</strong></td><td>{SERIAL_NUMBER}</td></tr>
      <tr><td style="padding: 6px 0;"><strong>Location:</strong></td><td>{LOCATION}</td></tr>
      <tr><td style="padding: 6px 0;"><strong>Days Remaining:</strong></td><td><strong>{DAYS_REMAINING} days</strong></td></tr>
      <tr><td style="padding: 6px 0;"><strong>Recommended Kit:</strong></td><td>{REPLACEMENT_PART_SKU}</td></tr>
      <tr><td style="padding: 6px 0;"><strong>Projected Replacement Date:</strong></td><td>{replacement_date}</td></tr>
    </table>

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ccc;">

    <p style="font-size: 0.9em; color: #555;">
      This message was automatically generated by the Energy Conversion Status 
      Monitoring System for demonstration purposes.
    </p>

  </div>
</body>
</html>
"""


def send_demo_email():
    recipient = getattr(settings, "DEFAULT_TEST_EMAIL", None)
    if recipient is None:
        raise RuntimeError("DEFAULT_TEST_EMAIL is not defined in settings.")

    subject = "Maintenance Alert: Water Heater Near Replacement Threshold"

    today = date.today()
    replacement_date = (today + timedelta(days=DAYS_REMAINING)).strftime("%Y-%m-%d")

    text_body = _build_plaintext_body(replacement_date)
    html_body = _build_html_body(replacement_date)

    msg = EmailMultiAlternatives(
        subject=subject,
        body=text_body,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[recipient],
    )

    msg.attach_alternative(html_body, "text/html")
    return msg.send(fail_silently=False)
